//! The lockfile, `loadout.lock`: the commit of every applied
//! source and the content hash of every resolved item.

use serde::{Deserialize, Serialize};

use crate::ModelError;
use crate::config::normalize_url;

pub const LOCK_VERSION: u32 = 1;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct Lock {
    pub version: u32,
    #[serde(default, rename = "source", skip_serializing_if = "Vec::is_empty")]
    pub sources: Vec<LockedSource>,
    #[serde(default, rename = "item", skip_serializing_if = "Vec::is_empty")]
    pub items: Vec<LockedItem>,
}

impl Default for Lock {
    fn default() -> Self {
        Lock {
            version: LOCK_VERSION,
            sources: Vec::new(),
            items: Vec::new(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct LockedSource {
    pub url: String,
    /// Source id from its `LOADOUT.md`.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub name: String,
    /// Full commit SHA that is applied.
    pub commit: String,
    /// When this commit was fetched (RFC 3339, UTC).
    pub fetched_at: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct LockedItem {
    /// `source:kind/name`.
    pub id: String,
    /// `blake3:<hex>` over the item's files.
    pub content_hash: String,
}

impl Lock {
    pub fn parse(text: &str) -> Result<Self, ModelError> {
        let lock: Lock = toml::from_str(text).map_err(|e| ModelError::Lock(e.to_string()))?;
        if lock.version != LOCK_VERSION {
            return Err(ModelError::Lock(format!(
                "unsupported version {} (this build reads version {LOCK_VERSION})",
                lock.version
            )));
        }
        Ok(lock)
    }

    /// Canonical text: sources by URL, items by id.
    pub fn to_toml(&self) -> String {
        let mut sorted = self.clone();
        sorted.sources.sort_by(|a, b| a.url.cmp(&b.url));
        sorted.items.sort_by(|a, b| a.id.cmp(&b.id));
        let body = toml::to_string(&sorted).expect("lock serializes");
        format!("# Generated by Loadout (`lo sync`). Do not edit.\n{body}")
    }

    /// The pinned source for `url` (compared after normalization).
    pub fn source(&self, url: &str) -> Option<&LockedSource> {
        let url = normalize_url(url);
        self.sources.iter().find(|s| normalize_url(&s.url) == url)
    }

    pub fn item(&self, id: &str) -> Option<&LockedItem> {
        self.items.iter().find(|i| i.id == id)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const EXAMPLE: &str = r#"version = 1
[[source]]
url = "https://github.com/acme/payments-skills"
commit = "3f9c2a0000000000000000000000000000000000"
fetched_at = "2026-09-22T20:00:00Z"
[[item]]
id = "payments-skills:skill/write-spec"
content_hash = "blake3:00"
"#;

    #[test]
    fn parses_example_and_round_trips() {
        let lock = Lock::parse(EXAMPLE).unwrap();
        assert_eq!(lock.sources[0].commit.len(), 40);
        assert_eq!(lock.sources[0].name, "");
        assert!(
            lock.source("https://github.com/acme/payments-skills.git/")
                .is_some()
        );
        assert!(lock.item("payments-skills:skill/write-spec").is_some());
        let text = lock.to_toml();
        assert!(text.starts_with("# Generated by Loadout"));
        assert_eq!(Lock::parse(&text).unwrap(), lock);
    }

    #[test]
    fn canonical_order() {
        let mut lock = Lock::default();
        for id in ["b:skill/x", "a:skill/y"] {
            lock.items.push(LockedItem {
                id: id.into(),
                content_hash: "blake3:0".into(),
            });
        }
        let text = lock.to_toml();
        assert!(text.find("a:skill/y").unwrap() < text.find("b:skill/x").unwrap());
    }

    #[test]
    fn rejects_other_versions_and_unknown_keys() {
        assert!(Lock::parse("version = 2\n").is_err());
        assert!(Lock::parse("version = 1\nextra = 1\n").is_err());
        assert_eq!(Lock::parse("version = 1\n").unwrap(), Lock::default());
    }
}
