[package]
name = "loadout-search"
description = "Loadout item search index"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
nucleo-matcher.workspace = true
schemars.workspace = true
serde.workspace = true

[lints]
workspace = true
